server:
  port: 7171

logging:
  level:
    com.vendor.management.system: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql