version: '3.8'

services:
  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
      args:
        CONJUR_ACCOUNT: ${CONJUR_ACCOUNT}
        CONJUR_APPLIANCE_URL: ${CONJUR_APPLIANCE_URL}
        CONJUR_DATABASE_CONFIG_VERSION: ${CONJUR_DATABASE_CONFIG_VERSION}
        CONJUR_AUTHN_LOGIN_HOST_DATABASE_CONFIG: ${CONJUR_AUTHN_LOGIN_HOST_DATABASE_CONFIG}
        CONJUR_AUTHN_API_KEY_HOST_DATABASE_CONFIG: ${CONJUR_AUTHN_API_KEY_HOST_DATABASE_CONFIG}
        CONJUR_VARIABLE_KEYCLOAK_POSTRESQL_HOST: ${CONJUR_VARIABLE_KEYCLOAK_POSTRESQL_HOST}
        CONJUR_VARIABLE_KEYCLOAK_POSTRESQL_PORT: ${CONJUR_VARIABLE_KEYCLOAK_POSTRESQL_PORT}
        CONJUR_VARIABLE_POSTRESQL_USERNAME: ${CONJUR_VARIABLE_POSTRESQL_USERNAME}
        CONJUR_VARIABLE_POSTRESQL_PASSWORD: ${CONJUR_VARIABLE_POSTRESQL_PASSWORD}
        CONJUR_KEYCLOAK_CONFIG_VERSION: ${CONJUR_KEYCLOAK_CONFIG_VERSION}
        CONJUR_AUTHN_LOGIN_HOST_KEYCLOAK_CONFIG: ${CONJUR_AUTHN_LOGIN_HOST_KEYCLOAK_CONFIG}
        CONJUR_AUTHN_API_KEY_HOST_KEYCLOAK_CONFIG: ${CONJUR_AUTHN_API_KEY_HOST_KEYCLOAK_CONFIG}
        CONJUR_VARIABLE_KEYCLOAK_ADMIN_USER: ${CONJUR_VARIABLE_KEYCLOAK_ADMIN_USER}
        CONJUR_VARIABLE_KEYCLOAK_ADMIN_PASSWORD: ${CONJUR_VARIABLE_KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8383:8080"
    environment:
      - "KEYCLOAK_DATABASE_VENDOR=postgresql"
      - "KEYCLOAK_DATABASE_NAME=keycloak_bitnami"
    volumes:
      - "./keycloak/keycloak-custom-spi-1.0.jar:/opt/bitnami/keycloak/providers/keycloak-custom-spi-1.0.jar"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}